feature: localisation
isac-nitkkr/node-modules pull request #27
Opened 2024-01-24 15:24 UTC by MohitMahipal

Added localisation to NIT KKR website.

2024-01-28 08:16 UTC, GetPsyched commented
Use this in the components and the 404 page instead of misc text

2024-01-28 08:19 UTC, GetPsyched requested changes

2024-01-28 08:19 UTC, GetPsyched commented on app/[lang]/dictionaries.ts
> +
Not required
```suggestion
```

2024-01-28 08:19 UTC, GetPsyched commented on app/[lang]/dictionaries.ts
> +  "hi-IN": () => import('./dictionaries/hi.json').then((module) => module.default),
```suggestion
  "en-GB": () => import('./locales/en.json').then((module) => module.default),
  "hi-IN": () => import('./locales/hi.json').then((module) => module.default),
```

2024-01-28 08:19 UTC, GetPsyched commented on app/[lang]/dictionaries.ts
> +export const getDictionary = async (locale: string): Promise<DictionaryInterface> => {
```suggestion
export const getLocale = async (locale: string): Promise<DictionaryInterface> => {
```

2024-01-28 15:15 UTC, Maan2003 commented on app/[lang]/dictionaries/hi.json
> +  }
missing new line, ditto for some other files

2024-01-28 15:15 UTC, Maan2003 commented on middleware.ts
> +let locales: string[] = ["en-GB", "hi-IN"];
const

2024-01-28 15:15 UTC, Maan2003 commented on middleware.ts
> +    }}).languages();
format

2024-01-28 15:15 UTC, Maan2003 commented on app/[lang]/dictionaries.ts
> +interface DictionaryInterface {
```suggestion
interface Dictionary {
```

2024-01-28 15:15 UTC, Maan2003 commented on app/[lang]/dictionaries.ts
> +  [k: string]: any;
```suggestion
  [k: string]: string;
```

2024-01-29 20:35 UTC, Maan2003 commented on app/[lang]/dictionaries.ts
> +  [k: string]: () => Promise<Obj<Obj<string>>>;
what, looks incorrect

2024-01-29 20:35 UTC, Maan2003 commented on app/[lang]/dictionaries/en.json
> +  }
why not, you get a flat type then
```suggestion
  "products.cart": "Mohit",
```

2024-01-30 04:10 UTC, Maan2003 commented on app/[lang]/dictionaries.ts
> +  [k: string]: () => Promise<Obj<Obj<string>>>;
better to use inferred types here. so you will get completions on the items in dictionary

2024-01-31 10:15 UTC, GetPsyched commented on components/work-in-progress.tsx
> -    <div className="m-auto max-w-fit text-center">
Why are we removing the styling??

2024-01-31 10:19 UTC, Maan2003 approved these changes

2024-01-31 10:19 UTC, MohitMahipal commented on components/work-in-progress.tsx
> -    <div className="m-auto max-w-fit text-center">
fixed

2024-01-31 10:40 UTC, Maan2003 commented on middleware.ts
> +    }}).languages();
why is `npm run format` not fixing this

cc @GetPsyched

2024-02-01 10:43 UTC, Maan2003 commented
feels like prop drilling

2024-02-01 10:44 UTC, GetPsyched commented
> feels like prop drilling

Not passing those props. NextJS directly injects props to page.tsx files which exist in the route path

2024-02-02 10:38 UTC, Maan2003 commented
what, i imagine every component needs translation, so you have to pass this lang prop to every component

--

this is not how i have seen l10n done,  usually there is function `t` that returns a translate version. `t` doesn't take lang as a paramater, it is somehow global state.

2024-02-02 12:32 UTC, GetPsyched commented
> `t` doesn't take lang as a paramater, it is somehow global state.

That somehow is with the use of the `useContext` hook. Which is a feature that requires the components to be client-side. Beats the purpose of SSR. If there's an alternative, I'm open to it.

2024-02-12 20:07 UTC, GetPsyched approved these changes
A bunch of things remain untranslated but that's out of scope of this PR.

2024-02-12 20:07 UTC, merged