Feature/GenericInputs
isac-nitkkr/node-modules pull request #62
Opened 2024-02-02 15:27 UTC by geekysilento

![image](https://github.com/isac-nitkkr/node-modules/assets/125768789/a534e798-6cc6-4a67-8619-297319ef738d)

Ignore the styling inconsistencies, will address them in a future commit

To do:

- Time input field
- Fetch countries for telephone, maybe using a external library like https://www.npmjs.com/package/react-phone-number-input would be better? 

Any advice is appreciated.

2024-02-02 16:06 UTC, GetPsyched requested changes

2024-02-02 16:06 UTC, GetPsyched commented on components/inputs/Visualizer.tsx
is this gonna be dumped later?

2024-02-02 16:06 UTC, GetPsyched commented on components/inputs/date.tsx
> +import * as React from 'react';
IDT this is needed

2024-02-02 16:06 UTC, GetPsyched commented on components/inputs/select.tsx
> +  },
```suggestion
  { id: 'recents', label: 'Recents' },
```

2024-02-02 16:06 UTC, GetPsyched commented on components/inputs/telephone.tsx
> +import { useState } from 'react';
```suggestion

import { useState } from 'react';
```

2024-02-06 09:54 UTC, geekysilento commented on components/inputs/Visualizer.tsx
yes, that component is just to visualize the inputs

2024-02-06 15:56 UTC, GetPsyched commented on app/page.tsx
> -      <Visualizer />
uh?

2024-02-07 10:28 UTC, closed without merging